//
//  MediaType.swift
//  Pilot
//
//  Created by Wesley Cope on 12/10/15.
//  Copyright © 2015 Wess Cope. All rights reserved.
//

import Foundation

public enum MediaType : String {
    case acx        = "application/internet-property-stream"
    case aif        = "audio/x-aiff"
    case asf        = "video/x-ms-asf"
    case au         = "audio/basic"
    case avi        = "video/x-msvideo"
    case axs        = "application/olescript"
    case bcpio      = "application/x-bcpio"
    case bmp        = "image/bmp"
    case cat        = "application/vnd.ms-pkiseccat"
    case cdf        = "application/x-netcdf"
    case cer        = "application/x-x509-ca-cert"
    case clp        = "application/x-msclip"
    case cmx        = "image/x-cmx"
    case cod        = "image/cis-cod"
    case crd        = "application/x-mscardfile"
    case crl        = "application/pkix-crl"
    case csh        = "application/x-csh"
    case css        = "text/css"
    case dcr        = "application/x-director"
    case dll        = "application/x-msdownload"
    case doc        = "application/msword"
    case dvi        = "application/x-dvi"
    case etx        = "text/x-setext"
    case evy        = "application/envoy"
    case fif        = "application/fractals"
    case gif        = "image/gif"
    case gtar       = "application/x-gtar"
    case gz         = "application/x-gzip"
    case hdf        = "application/x-hdf"
    case hlp        = "application/winhlp"
    case hqx        = "application/mac-binhex40"
    case hta        = "application/hta"
    case htc        = "text/x-component"
    case html       = "text/html"
    case htt        = "text/webviewhtml"
    case ico        = "image/x-icon"
    case ief        = "image/ief"
    case iii        = "application/x-iphone"
    case ins        = "application/x-internet-signup"
    case jfif       = "image/pipeg"
    case jpg        = "image/jpeg"
    case js         = "application/x-javascript"
    case latex      = "application/x-latex"
    case lsf        = "video/x-la-asf"
    case m13        = "application/x-msmediaview"
    case m3u        = "audio/x-mpegurl"
    case man        = "application/x-troff-man"
    case mdb        = "application/x-msaccess"
    case me         = "application/x-troff-me"
    case mht        = "message/rfc822"
    case mid        = "audio/mid"
    case mny        = "application/x-msmoney"
    case mov        = "video/quicktime"
    case movie      = "video/x-sgi-movie"
    case mp3        = "audio/mpeg"
    case mpa        = "video/mpeg"
    case mpp        = "application/vnd.ms-project"
    case ms         = "application/x-troff-ms"
    case msg        = "application/vnd.ms-outlook"
    case oda        = "application/oda"
    case p10        = "application/pkcs10"
    case p12        = "application/x-pkcs12"
    case p7b        = "application/x-pkcs7-certificates"
    case p7c        = "application/x-pkcs7-mime"
    case p7r        = "application/x-pkcs7-certreqresp"
    case p7s        = "application/x-pkcs7-signature"
    case pbm        = "image/x-portable-bitmap"
    case pdf        = "application/pdf"
    case pgm        = "image/x-portable-graymap"
    case pko        = "application/ynd.ms-pkipko"
    case pnm        = "image/x-portable-anymap"
    case pot        = "application/vnd.ms-powerpoint"
    case ppm        = "image/x-portable-pixmap"
    case prf        = "application/pics-rules"
    case ps         = "application/postscript"
    case ras        = "image/x-cmu-raster"
    case rgb        = "image/x-rgb"
    case roff       = "application/x-troff"
    case rtf        = "application/rtf"
    case rtx        = "text/richtext"
    case scd        = "application/x-msschedule"
    case sct        = "text/scriptlet"
    case setpay     = "application/set-payment-initiation"
    case setreg     = "application/set-registration-initiation"
    case sh         = "application/x-sh"
    case shar       = "application/x-shar"
    case sit        = "application/x-stuffit"
    case spl        = "application/futuresplash"
    case src        = "application/x-wais-source"
    case sst        = "application/vnd.ms-pkicertstore"
    case stl        = "application/vnd.ms-pkistl"
    case sv4cpio    = "application/x-sv4cpio"
    case sv4crc     = "application/x-sv4crc"
    case svg        = "image/svg+xml"
    case swf        = "application/x-shockwave-flash"
    case tar        = "application/x-tar"
    case tcl        = "application/x-tcl"
    case tex        = "application/x-tex"
    case texi       = "application/x-texinfo"
    case tgz        = "application/x-compressed"
    case tiff       = "image/tiff"
    case trm        = "application/x-msterminal"
    case tsv        = "text/tab-separated-values"
    case txt        = "text/plain"
    case uls        = "text/iuls"
    case ustar      = "application/x-ustar"
    case vcf        = "text/x-vcard"
    case vrml       = "x-world/x-vrml"
    case wav        = "audio/x-wav"
    case wmf        = "application/x-msmetafile"
    case wri        = "application/x-mswrite"
    case xbm        = "image/x-xbitmap"
    case xslt       = "application/vnd.ms-excel"
    case xpm        = "image/x-xpixmap"
    case xwd        = "image/x-xwindowdump"
    case z          = "application/x-compress"
    case zip        = "application/zip"
    case json       = "application/json"
    case octstream  = "application/octet-stream"
    
    //MARK: - Aliases 
    public static let mpe:MediaType     = mpa
    public static let mpeg:MediaType    = mpa
    public static let mpg:MediaType     = mpa
    public static let mpv2:MediaType    = mpa
    public static let mp2:MediaType     = mpa
    public static let aifc:MediaType    = aif
    public static let aiff:MediaType    = aif
    public static let asr:MediaType     = asf
    public static let asx:MediaType     = asf
    public static let c:MediaType       = txt
    public static let crt:MediaType     = cer
    public static let der:MediaType     = cer
    public static let dot:MediaType     = doc
    public static let wrl:MediaType     = vrml
    public static let wrz:MediaType     = vrml
    public static let xaf:MediaType     = vrml
    public static let xof:MediaType     = vrml
    public static let xla:MediaType     = xslt
    public static let xlc:MediaType     = xslt
    public static let xlm:MediaType     = xslt
    public static let xls:MediaType     = xslt
    public static let xlt:MediaType     = xslt
    public static var xlw:MediaType     = xslt
    public static let pps:MediaType     = pot
    public static let ppt:MediaType     = pot
    public static let h:MediaType       = txt
    public static let htm:MediaType     = html
    public static let jpe:MediaType     = jpg
    public static let jpeg:MediaType    = jpg
    public static let stm:MediaType     = html
    public static let texinfo:MediaType = texi
    public static let tif:MediaType     = tiff
    public static let p7m:MediaType     = p7c
    public static let dms:MediaType     = octstream
    public static let eps:MediaType     = ps
    public static let exe:MediaType     = octstream
    public static let isp:MediaType     = ins
    public static let lha:MediaType     = octstream
    public static let lsx:MediaType     = lsf
    public static let lzh:MediaType     = octstream
    public static let m14:MediaType     = m13
    public static let pfx:MediaType     = p12
    public static let spc:MediaType     = p7b
    public static let bas:MediaType     = txt
    public static let snd:MediaType     = au
    public static let qt:MediaType      = mov
    public static let ai:MediaType      = ps
    public static let flr:MediaType     = vrml
    public static let rmi:MediaType     = mid
    public static let bin:MediaType     = octstream
}